#if !defined(AFX_AXES1_H__2080AFF1_5CE2_4691_A18B_B213F9D4CDC7__INCLUDED_)
#define AFX_AXES1_H__2080AFF1_5CE2_4691_A18B_B213F9D4CDC7__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CAxis1;

/////////////////////////////////////////////////////////////////////////////
// CAxes1 wrapper class

class CAxes1 : public COleDispatchDriver
{
public:
	CAxes1() {}		// Calls COleDispatchDriver default constructor
	CAxes1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAxes1(const CAxes1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CAxis1 GetLeft();
	CAxis1 GetRight();
	CAxis1 GetTop();
	CAxis1 GetBottom();
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	CAxis1 GetDepth();
	BOOL GetDrawAxesBeforeSeries();
	void SetDrawAxesBeforeSeries(BOOL bNewValue);
	long AddCustom(BOOL IsHorizontal);
	CAxis1 GetCustom(long CustomAxisIndex);
	long GetCustomCount();
	void RemoveCustom(long CustomAxisIndex);
	void RemoveAllCustom();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AXES1_H__2080AFF1_5CE2_4691_A18B_B213F9D4CDC7__INCLUDED_)
