#if !defined(AFX_SCROLL1_H__0CC0F5D4_25F2_4F2D_A2DE_48CDAE36D6F4__INCLUDED_)
#define AFX_SCROLL1_H__0CC0F5D4_25F2_4F2D_A2DE_48CDAE36D6F4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CScroll1 wrapper class

class CScroll1 : public COleDispatchDriver
{
public:
	CScroll1() {}		// Calls COleDispatchDriver default constructor
	CScroll1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CScroll1(const CScroll1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetEnable();
	void SetEnable(long nNewValue);
	long GetMouseButton();
	void SetMouseButton(long nNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SCROLL1_H__0CC0F5D4_25F2_4F2D_A2DE_48CDAE36D6F4__INCLUDED_)
